# Generated by Django 4.2.5 on 2023-10-05 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_items_cart_cart_items_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='Total_price',
        ),
    ]
