# Generated by Django 4.2.5 on 2023-10-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_items_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
