# Generated by Django 4.2.5 on 2023-10-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_alter_shipping_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ship_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.BigIntegerField()),
                ('Location', models.CharField(max_length=50)),
                ('Shipping_address', models.CharField(max_length=100)),
            ],
        ),
    ]
