# Generated by Django 4.2.5 on 2023-10-06 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_items_customer_and_more'),
        ('orders', '0002_remove_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact',
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart_items'),
        ),
    ]
