# Generated by Django 4.2.5 on 2023-10-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_items_customer_and_more'),
        ('orders', '0003_remove_order_billing_address_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='cart.cart_items'),
        ),
    ]
