# Generated by Django 4.2.5 on 2023-10-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(default=1, upload_to='user_profile'),
            preserve_default=False,
        ),
    ]
